### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by ErikCH** [terminalvelocity/seeds.js#44]
I just installed seeds on my Ubuntu instance and I get this error when I try to run it.

$ seeds new project
`
class SeedsCLI extends Cli {
^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/bravo/.nvm/versions/node/v0.12.0/lib/node_modules/seeds/bin/seeds:13:11
    at /home/bravo/.nvm/versions/node/v0.12.0/lib/node_modules/seeds/node_modules/resolve/lib/async.js:46:14
    at process (/home/bravo/.nvm/versions/node/v0.12.0/lib/node_modules/seeds/node_modules/resolve/lib/async.js:173:43)
`

**Comment by austinpray** [comment]
Possibly because it requires iojs instead of 0.12.

`nvm install iojs`

**Comment by jhliberty** [comment]
Added babel/npm script to compile es6 into es5 so seeds can be run on node. 

iojs 2+ removed as dependency 

3be3ed3a59a6aac5682b1e3c8e6f228f70883131
